### ISSUE TITLE
ActionController::Session::CookieStore::CookieOverflow

### ISSUE THREAD

**Issue by dumbledore** [evan/mongrel#12]
After running Mongrel for the n-th time (for it needs restarting it after making changes in my models) I was welcomed with the message:

> /!\ FAILSAFE /!\  Wed Oct 27 23:02:49 +0300 2010
>   Status: 500 Internal Server Error
>   ActionController::Session::CookieStore::CookieOverflow
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.10/lib/action_controller/session/cookie_store.rb:112:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.10/lib/action_controller/failsafe.rb:26:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/lock.rb:11:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/lock.rb:11:in 'synchronize'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/lock.rb:11:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.10/lib/action_controller/dispatcher.rb:114:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.10/lib/action_controller/reloader.rb:34:in 'run'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.10/lib/action_controller/dispatcher.rb:108:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.10/lib/rails/rack/static.rb:31:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/urlmap.rb:47:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/urlmap.rb:41:in 'each'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/urlmap.rb:41:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.10/lib/rails/rack/log_tailer.rb:17:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/content_length.rb:13:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/chunked.rb:15:in 'call'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/handler/mongrel.rb:67:in 'process'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb:159:in 'process_client'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb:158:in 'each'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb:158:in 'process_client'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb:285:in 'run'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb:285:in 'initialize'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb:285:in 'new'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb:285:in 'run'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb:268:in 'initialize'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb:268:in 'new'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mingw32/lib/mongrel.rb:268:in 'run'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/handler/mongrel.rb:38:in 'run'
>   C:/Program Files/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.10/lib/commands/server.rb:111
>   C:/Program Files/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in 'gem_original_require'
>   C:/Program Files/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in 'require'
>   S:/Dumbledore/work/web/rails/albite-r2/script/server:3
>   -e:1:in 'load'
>   -e:1

**Comment by dumbledore** [comment]
Sorry, obviously my mistake.
